export const BIBLE_VERSES = [
  "O Senhor é o meu pastor, nada me faltará. (Salmo 23:1)",
  "Tudo posso naquele que me fortalece. (Filipenses 4:13)",
  "O meu socorro vem do Senhor, que fez o céu e a terra. (Salmo 121:2)",
  "Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará. (Salmo 37:5)",
  "Lâmpada para os meus pés é tua palavra, e luz para o meu caminho. (Salmo 119:105)",
  "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito. (João 3:16)",
  "Alegrai-vos sempre no Senhor; outra vez digo, alegrai-vos. (Filipenses 4:4)",
  "O Senhor te abençoe e te guarde. (Números 6:24)",
  "Buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas. (Mateus 6:33)",
  "A paz de Deus, que excede todo o entendimento, guardará os vossos corações. (Filipenses 4:7)",
  "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia. (Salmo 46:1)",
  "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor. (Colossenses 3:23)",
  "Espero no Senhor com toda a minha alma, e na sua palavra aguardo. (Salmo 130:5)",
  "Pois eu bem sei os planos que tenho para vós, diz o Senhor, planos de paz. (Jeremias 29:11)",
  "O Senhor é bom, uma fortaleza no dia da angústia. (Naum 1:7)",
  "Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. (Provérbios 3:5)",
  "Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco. (1 Tessalonicenses 5:18)",
  "Não fui eu que lhe ordenei? Seja forte e corajoso! (Josué 1:9)",
  "O fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade. (Gálatas 5:22)",
  "Mil cairão ao teu lado, e dez mil à tua direita, mas não chegará a ti. (Salmo 91:7)",
  "A ti, Senhor, elevo a minha alma. (Salmo 25:1)",
  "Ensina-nos a contar os nossos dias, para que alcancemos coração sábio. (Salmo 90:12)",
  "O amor é sofredor, o amor é benigno; não é invejoso; o amor não trata com leviandade. (1 Coríntios 13:4)",
  "Deem graças ao Senhor, porque ele é bom; o seu amor dura para sempre. (Salmo 136:1)",
  "Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês. (1 Pedro 5:7)",
  "Honra a teu pai e a tua mãe... para que te vá bem e vivas muito tempo sobre a terra. (Efésios 6:2-3)",
  "A palavra do Senhor permanece para sempre. (1 Pedro 1:25)",
  "O Senhor está perto de todos os que o invocam, de todos os que o invocam em verdade. (Salmo 145:18)",
  "Grandes coisas fez o Senhor por nós, pelas quais estamos alegres. (Salmo 126:3)",
  "Se Deus é por nós, quem será contra nós? (Romanos 8:31)",
  "Nem só de pão viverá o homem, mas de toda a palavra que sai da boca de Deus. (Mateus 4:4)",
  "Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta será aberta. (Mateus 7:7)",
  "O coração alegre serve de bom remédio. (Provérbios 17:22)",
  "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum. (Salmo 23:4)",
  "Crê no Senhor Jesus Cristo e serás salvo, tu e a tua casa. (Atos 16:31)",
  "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará. (Salmo 91:1)",
  "Sabe que o Senhor é Deus; foi ele quem nos fez, e dele somos. (Salmo 100:3)",
  "No amor não há temor, antes o perfeito amor lança fora o temor. (1 João 4:18)",
  "O Senhor é a minha luz e a minha salvação; a quem temerei? (Salmo 27:1)",
  "Para Deus nada é impossível. (Lucas 1:37)",
  "A graça do Senhor Jesus Cristo seja com todos vocês. (Apocalipse 22:21)",
  "Bem-aventurados os limpos de coração, porque eles verão a Deus. (Mateus 5:8)",
  "Guarda o teu coração, porque dele procedem as fontes da vida. (Provérbios 4:23)",
  "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei. (Mateus 11:28)",
  "Faze-me ouvir a tua benignidade pela manhã, pois em ti confio. (Salmo 143:8)",
  "Eu sou o caminho, e a verdade e a vida. (João 14:6)",
  "Pedi, e dar-se-vos-á; buscai, e encontrareis. (Mateus 7:7)",
  "O Senhor é a minha força e o meu escudo; nele confiou o meu coração. (Salmo 28:7)",
  "A fé é o firme fundamento das coisas que se esperam. (Hebreus 11:1)",
  "E conhecereis a verdade, e a verdade vos libertará. (João 8:32)",
  "Provem e vejam como o Senhor é bom. (Salmo 34:8)",
  "Consagre ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos. (Provérbios 16:3)",
  "Ficai firmes na fé; portai-vos varonilmente, e fortalecei-vos. (1 Coríntios 16:13)",
  "O Senhor lutará por vocês; tão-somente acalmem-se. (Êxodo 14:14)",
  "Combati o bom combate, acabei a carreira, guardei a fé. (2 Timóteo 4:7)",
  "Deus nos amou primeiro. (1 João 4:19)",
  "Agrada-te do Senhor, e ele satisfará os desejos do teu coração. (Salmo 37:4)",
  "Eu e a minha casa serviremos ao Senhor. (Josué 24:15)",
  "Justificados, pois, pela fé, temos paz com Deus. (Romanos 5:1)",
  "Tudo tem o seu tempo determinado, e há tempo para todo o propósito debaixo do céu. (Eclesiastes 3:1)",
  "Deus é amor. (1 João 4:8)",
  "O temor do Senhor é o princípio da sabedoria. (Salmo 111:10)",
  "Cantai ao Senhor um cântico novo. (Salmo 98:1)",
  "O Senhor te guardará de todo o mal; guardará a tua alma. (Salmo 121:7)",
  "A palavra de Cristo habite em vós abundantemente. (Colossenses 3:16)",
  "Em paz me deito e logo adormeço, pois só tu, Senhor, me fazes viver em segurança. (Salmo 4:8)",
  "Sê fiel até à morte, e dar-te-ei a coroa da vida. (Apocalipse 2:10)",
  "Não se turbe o vosso coração; credes em Deus, crede também em mim. (João 14:1)",
  "Somente em Deus a minha alma espera silenciosa; dele vem a minha salvação. (Salmo 62:1)",
  "Dá-me, filho meu, o teu coração. (Provérbios 23:26)",
  "Os que esperam no Senhor renovarão as suas forças. (Isaías 40:31)",
  "A mansidão da sabedoria. (Tiago 3:13)",
  "Toda a Escritura é divinamente inspirada. (2 Timóteo 3:16)",
  "Abençoarei o Senhor em todo o tempo. (Salmo 34:1)",
  "Eis que estou convosco todos os dias. (Mateus 28:20)",
  "A graça de nosso Senhor Jesus Cristo seja convosco. (1 Tessalonicenses 5:28)",
  "Prepara-te para te encontrares com o teu Deus. (Amós 4:12)",
  "O Senhor conhece os que lhe pertencem. (2 Timóteo 2:19)",
  "Deus suprirá todas as vossas necessidades. (Filipenses 4:19)",
  "Bem-aventurados os que promovem a paz. (Mateus 5:9)",
  "Fugi das paixões da mocidade. (2 Timóteo 2:22)",
  "Não nos cansemos de fazer o bem. (Gálatas 6:9)",
  "Andai em amor. (Efésios 5:2)",
  "Aquietai-vos, e sabei que eu sou Deus. (Salmo 46:10)",
  "O espírito, na verdade, está pronto, mas a carne é fraca. (Mateus 26:41)",
  "Vós sois o sal da terra. (Mateus 5:13)",
  "Vós sois a luz do mundo. (Mateus 5:14)",
  "O Senhor é tardio em irar-se, mas grande em poder. (Naum 1:3)",
  "A benignidade do Senhor dura para sempre. (Salmo 103:17)",
  "A nossa cidadania está nos céus. (Filipenses 3:20)",
  "Cristo em vós, esperança da glória. (Colossenses 1:27)",
  "Sede vós também santos em toda a vossa maneira de viver. (1 Pedro 1:15)",
  "A palavra da cruz é loucura para os que perecem. (1 Coríntios 1:18)",
  "Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos. (João 15:13)",
  "Eu sou a luz do mundo; quem me segue não andará em trevas. (João 8:12)",
  "Pelas suas pisaduras fomos sarados. (Isaías 53:5)",
  "O Senhor é a minha porção, diz a minha alma. (Lamentações 3:24)",
  "Grande é a tua fidelidade. (Lamentações 3:23)",
  "Não retires de mim o teu Espírito Santo. (Salmo 51:11)",
  "Cria em mim, ó Deus, um coração puro. (Salmo 51:10)",
  "Alegrei-me quando me disseram: Vamos à casa do Senhor. (Salmo 122:1)",
  "Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus. (1 Coríntios 10:31)",
  "O Senhor é a minha rocha, a minha fortaleza e o meu libertador. (Salmo 18:2)",
  "A minha alma anseia pelo Senhor, mais do que os guardas pelo romper da manhã. (Salmo 130:6)",
  "O Senhor cumprirá o seu propósito para comigo; o teu amor, Senhor, dura para sempre. (Salmo 138:8)",
  "Ensina-me a fazer a tua vontade, pois tu és o meu Deus; guie-me o teu bom Espírito por terreno plano. (Salmo 143:10)",
  "Grande é o nosso Soberano e tremendo é o seu poder; a sua sabedoria não tem limite. (Salmo 147:5)",
  "O Senhor é bom para com todos; a sua compaixão alcança todas as suas criaturas. (Salmo 145:9)",
  "O justo florescerá como a palmeira; crescerá como o cedro no Líbano. (Salmo 92:12)",
  "O Senhor é o meu escudo e a minha glória, e o que exalta a minha cabeça. (Salmo 3:3)",
  "Como são preciosos para mim os teus pensamentos, ó Deus! Como é grande a soma deles! (Salmo 139:17)",
  "Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece as minhas inquietações. (Salmo 139:23)",
  "O que atenta para a palavra achará o bem, e o que confia no Senhor será bem-aventurado. (Provérbios 16:20)",
  "A sabedoria do homem lhe dá paciência; sua glória é relevar as ofensas. (Provérbios 19:11)",
  "Como águas profundas são os propósitos do coração do homem, mas o homem de inteligência sabe extraí-los. (Provérbios 20:5)",
  "O caminho do Senhor é fortaleza para os íntegros. (Provérbios 10:29)",
  "A bênção do Senhor traz riqueza, e não inclui dor alguma. (Provérbios 10:22)",
  "Quem segue a justiça e a lealdade encontra vida, justiça e honra. (Provérbios 21:21)",
  "Confie ao Senhor as suas obras, e os seus pensamentos serão estabelecidos. (Provérbios 16:3)",
  "O homem de coração sábio é chamado prudente, e a doçura dos lábios aumenta o saber. (Provérbios 16:21)",
  "A esperança que se adia adoece o coração, mas o desejo cumprido é árvore de vida. (Provérbios 13:12)",
  "A resposta delicada aplaca a ira, mas a palavra dura desperta o furor. (Provérbios 15:1)",
  "Os olhos do Senhor estão em todo lugar, contemplando os maus e os bons. (Provérbios 15:3)",
  "O coração alegre afeiçoa o rosto, mas pela dor do coração o espírito se abate. (Provérbios 15:13)",
  "Todos os dias do aflito são maus, mas o coração alegre tem um banquete contínuo. (Provérbios 15:15)",
  "Melhor é um prato de hortaliças onde há amor do que o boi gordo onde há ódio. (Provérbios 15:17)",
  "O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos. (Provérbios 16:9)",
  "Melhor é o que tarda em irar-se do que o forte, e o que domina o seu espírito do que o que toma uma cidade. (Provérbios 16:32)",
  "O amigo ama em todos os momentos; na desgraça ele se torna um irmão. (Provérbios 17:17)",
  "O nome do Senhor é uma torre forte; os justos correm para ela e estão seguros. (Provérbios 18:10)",
  "O homem de muitos amigos pode chegar à ruína, mas há amigo mais chegado do que um irmão. (Provérbios 18:24)",
  "A sabedoria é melhor do que as joias, e tudo o que se deseja não se pode comparar com ela. (Provérbios 8:11)",
  "Os passos do homem são dirigidos pelo Senhor; como, pois, entenderá o homem o seu próprio caminho? (Provérbios 20:24)",
  "Instrui o menino no caminho em que deve andar, e até quando for velho não se desviará dele. (Provérbios 22:6)",
  "Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo. (Provérbios 27:17)",
  "O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia. (Provérbios 28:13)",
  "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço. (Isaías 41:10)",
  "Porque eu, o Senhor teu Deus, te tomo pela tua mão direita; e te digo: Não temas, eu te ajudo. (Isaías 41:13)",
  "Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias. (Isaías 40:31)",
  "Não vos lembreis das coisas passadas, nem considereis as antigas; eis que faço uma coisa nova. (Isaías 43:18-19)",
  "Porque as montanhas se retirarão, e os outeiros seriam abalados; mas a minha benignidade não se retirará de ti. (Isaías 54:10)",
  "O Senhor guiará você continuamente, saciará os seus desejos em terras áridas e revigorará os seus ossos. (Isaías 58:11)",
  "Arrependei-vos, porque está próximo o reino dos céus. (Mateus 3:2)",
  "Portanto, não vos inquieteis com o dia de amanhã, pois o amanhã trará as suas próprias preocupações. (Mateus 6:34)",
  "Peçam, e lhes será dado; busquem, e encontrarão; batam, e a porta será aberta. (Mateus 7:7)",
  "Entrai pela porta estreita; porque larga é a porta, e espaçoso o caminho que conduz à perdição. (Mateus 7:13)",
  "Nem todo o que me diz: Senhor, Senhor! entrará no reino dos céus, mas aquele que faz a vontade de meu Pai. (Mateus 7:21)",
  "Portanto, quem ouve estas minhas palavras e as pratica é como um homem prudente que construiu a sua casa sobre a rocha. (Mateus 7:24)",
  "E Jesus, ouvindo isto, disse-lhes: Não necessitam de médico os sãos, mas, sim, os doentes. (Mateus 9:12)",
  "E todo aquele que der, embora seja apenas um copo de água fria a um destes pequeninos... não perderá o seu galardão. (Mateus 10:42)",
  "Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos darei descanso. (Mateus 11:28)",
  "Tomai sobre vós o meu jugo e aprendei de mim, porque sou manso e humilde de coração; e achareis descanso. (Mateus 11:29)",
  "Pois o meu jugo é suave, e o meu fardo é leve. (Mateus 11:30)",
  "Pois, qualquer que fizer a vontade de meu Pai que está nos céus, este é meu irmão, e irmã, e mãe. (Mateus 12:50)",
  "Pois que aproveita ao homem ganhar o mundo inteiro, se perder a sua alma? (Mateus 16:26)",
  "Porque, onde estiverem dois ou três reunidos em meu nome, aí estou eu no meio deles. (Mateus 18:20)",
  "Jesus olhou para eles e respondeu: Para o homem isso é impossível, mas para Deus todas as coisas são possíveis. (Mateus 19:26)",
  "Amarás o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todo o teu pensamento. (Mateus 22:37)",
  "Amarás o teu próximo como a ti mesmo. (Mateus 22:39)",
  "Passará o céu e a terra, mas as minhas palavras não passarão. (Mateus 24:35)",
  "Vigiai e orai, para que não entreis em tentação; na verdade, o espírito está pronto, mas a carne é fraca. (Mateus 26:41)",
  "Eis que eu estou convosco todos os dias, até a consumação dos séculos. Amém. (Mateus 28:20)",
  "Tudo o que pedirem em oração, creiam que já o receberam, e assim sucederá. (Marcos 11:24)",
  "Não temas, crê somente. (Marcos 5:36)",
  "Porque para Deus nada é impossível. (Lucas 1:37)",
  "Não julgueis, e não sereis julgados; não condeneis, e não sereis condenados; soltai, e soltar-vos-ão. (Lucas 6:37)",
  "Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordando vos deitarão no vosso regaço. (Lucas 6:38)",
  "O homem bom do bom tesouro do seu coração tira o bem. (Lucas 6:45)",
  "Pois o Filho do homem veio buscar e salvar o que se havia perdido. (Lucas 19:10)",
  "Mas a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus. (João 1:12)",
  "Aquele que crê no Filho tem a vida eterna. (João 3:36)",
  "Se alguém tiver sede, venha a mim e beba. (João 7:37)",
  "Eu sou a luz do mundo; quem me segue não andará em trevas, mas terá a luz da vida. (João 8:12)",
  "E conhecereis a verdade, e a verdade vos libertará. (João 8:32)",
  "Se, pois, o Filho vos libertar, verdadeiramente sereis livres. (João 8:36)",
  "Eu sou o bom Pastor; o bom Pastor dá a sua vida pelas ovelhas. (João 10:11)",
  "Eu vim para que tenham vida, e a tenham com abundância. (João 10:10)",
  "Eu sou a ressurreição e a vida; quem crê em mim, ainda que esteja morto, viverá. (João 11:25)",
  "Novo mandamento vos dou: que vos ameis uns aos outros; assim como eu vos amei. (João 13:34)",
  "Nisto todos conhecerão que sois meus discípulos, se vos amardes uns aos outros. (João 13:35)",
  "Não se turbe o vosso coração; credes em Deus, crede também em mim. (João 14:1)",
  "Eu sou o caminho, e a verdade e a vida; ninguém vem ao Pai, senão por mim. (João 14:6)",
  "Se me amais, guardareis os meus mandamentos. (João 14:15)",
  "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração. (João 14:27)",
  "Eu sou a videira, vós as varas; quem está em mim, e eu nele, esse dá muito fruto; porque sem mim nada podeis fazer. (João 15:5)",
  "Ninguém tem maior amor do que este: de dar alguém a sua vida pelos seus amigos. (João 15:13)",
  "Não me escolhestes vós a mim, mas eu vos escolhi a vós, e vos nomeei, para que vades e deis fruto. (João 15:16)",
  "Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo; eu venci o mundo. (João 16:33)",
  "Santifica-os na verdade; a tua palavra é a verdade. (João 17:17)",
  "Mas recebereis poder ao descer sobre vós o Espírito Santo, e sereis minhas testemunhas. (Atos 1:8)",
  "E acontecerá que todo aquele que invocar o nome do Senhor será salvo. (Atos 2:21)",
  "Mais importa obedecer a Deus do que aos homens. (Atos 5:29)",
  "Há maior felicidade em dar do que em receber. (Atos 20:35)",
  "Porque não me envergonho do evangelho de Cristo, pois é o poder de Deus para salvação de todo aquele que crê. (Romanos 1:16)",
  "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna, por Cristo Jesus nosso Senhor. (Romanos 6:23)",
  "E sabemos que todas as coisas contribuem juntamente para o bem daqueles que amam a Deus. (Romanos 8:28)",
  "Se Deus é por nós, quem será contra nós? (Romanos 8:31)",
  "Quem nos separará do amor de Cristo? A tribulação, ou a angústia, ou a perseguição, ou a fome, ou a nudez, ou o perigo? (Romanos 8:35)",
  "Mas em todas estas coisas somos mais do que vencedores, por aquele que nos amou. (Romanos 8:37)",
  "A saber: Se com a tua boca confessares ao Senhor Jesus... serás salvo. (Romanos 10:9)",
  "De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus. (Romanos 10:17)",
  "Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração. (Romanos 12:12)",
  "Se for possível, quanto depender de vós, tende paz com todos os homens. (Romanos 12:18)",
  "Não te deixes vencer do mal, mas vence o mal com o bem. (Romanos 12:21)",
  "O amor não faz mal ao próximo. De sorte que o cumprimento da lei é o amor. (Romanos 13:10)",
  "Acolham-se uns aos outros, como também Cristo nos acolheu para a glória de Deus. (Romanos 15:7)",
  "Que o Deus da esperança os encha de toda alegria e paz, por sua confiança nele. (Romanos 15:13)",
  "Porque a palavra da cruz é loucura para os que perecem; mas para nós, que somos salvos, é o poder de Deus. (1 Coríntios 1:18)",
  "Mas, como está escrito: As coisas que o olho não viu, e o ouvido não ouviu... são as que Deus preparou para os que o amam. (1 Coríntios 2:9)",
  "Porque ninguém pode pôr outro fundamento, além do que já está posto, o qual é Jesus Cristo. (1 Coríntios 3:11)",
  "Não sabeis vós que sois o templo de Deus e que o Espírito de Deus habita em vós? (1 Coríntios 3:16)",
  "Todas as coisas me são lícitas, mas nem todas as coisas convêm. (1 Coríntios 6:12)",
  "Fugi da prostituição. (1 Coríntios 6:18)",
  "Ou não sabeis que o vosso corpo é o templo do Espírito Santo, que habita em vós? (1 Coríntios 6:19)",
  "Portanto, quer comais quer bebais, ou façais outra qualquer coisa, fazei tudo para glória de Deus. (1 Coríntios 10:31)",
  "Seja o que for que façam, façam-no para a glória de Deus. (1 Coríntios 10:31)",
  "Ainda que eu falasse as línguas dos homens e dos anjos, e não tivesse amor, seria como o metal que soa. (1 Coríntios 13:1)",
  "O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece. (1 Coríntios 13:4)",
  "O amor não se porta com indecência, não busca os seus interesses, não se irrita, não suspeita mal. (1 Coríntios 13:5)",
  "O amor não folga com a injustiça, mas folga com a verdade; tudo sofre, tudo crê, tudo espera, tudo suporta. (1 Coríntios 13:6-7)",
  "O amor nunca falha. (1 Coríntios 13:8)",
  "Agora, pois, permanecem a fé, a esperança e o amor, estes três, mas o maior destes é o amor. (1 Coríntios 13:13)",
  "Sede vigilantes, permanecei firmes na fé, portai-vos varonilmente, fortalecei-vos. (1 Coríntios 16:13)",
  "Todas as vossas coisas sejam feitas com amor. (1 Coríntios 16:14)",
  "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda a consolação. (2 Coríntios 1:3)",
  "Porque andamos por fé, e não por vista. (2 Coríntios 5:7)",
  "Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo. (2 Coríntios 5:17)",
  "E ele disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. (2 Coríntios 12:9)",
  "Porque nada podemos contra a verdade, senão pela verdade. (2 Coríntios 13:8)",
  "A graça do Senhor Jesus Cristo, e o amor de Deus, e a comunhão do Espírito Santo sejam com todos vós. (2 Coríntios 13:13)",
  "Já estou crucificado com Cristo; e vivo, não mais eu, mas Cristo vive em mim. (Gálatas 2:20)",
  "Porque vós, irmãos, fostes chamados à liberdade. Não useis então da liberdade para dar ocasião à carne. (Gálatas 5:13)",
  "Digo, porém: Andai em Espírito, e não cumprireis a concupiscência da carne. (Gálatas 5:16)",
  "Mas o fruto do Espírito é: amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidão, domínio próprio. (Gálatas 5:22-23)",
  "Se vivemos em Espírito, andemos também em Espírito. (Gálatas 5:25)",
  "Levem os fardos uns dos outros e, assim, cumprirão a lei de Cristo. (Gálatas 6:2)",
  "E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido. (Gálatas 6:9)",
  "Porque pela graça sois salvos, por meio da fé; e isto não vem de vós, é dom de Deus. (Efésios 2:8)",
  "Não vem das obras, para que ninguém se glorie. (Efésios 2:9)",
  "Porque somos feitura sua, criados em Cristo Jesus para as boas obras. (Efésios 2:10)",
  "Esforcem-se para manter a unidade do Espírito pelo vínculo da paz. (Efésios 4:3)",
  "Irai-vos, e não pequeis; não se ponha o sol sobre a vossa ira. (Efésios 4:26)",
  "Toda a amargura, e ira, e cólera, e gritaria, e blasfêmia e toda a malícia sejam tiradas de entre vós. (Efésios 4:31)",
  "Antes sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros, como também Deus vos perdoou. (Efésios 4:32)",
  "Andem em amor, como também Cristo nos amou e se entregou por nós. (Efésios 5:2)",
  "Falando entre vós em salmos, e hinos, e cânticos espirituais; cantando e salmodiando ao Senhor no vosso coração. (Efésios 5:19)",
  "Dando sempre graças por tudo a nosso Deus e Pai, em nome de nosso Senhor Jesus Cristo. (Efésios 5:20)",
  "No demais, irmãos meus, fortalecei-vos no Senhor e na força do seu poder. (Efésios 6:10)",
  "Revesti-vos de toda a armadura de Deus, para que possais estar firmes contra as astutas ciladas do diabo. (Efésios 6:11)",
  "Tomando sobretudo o escudo da fé, com o qual podereis apagar todos os dardos inflamados do maligno. (Efésios 6:16)",
  "Honra a teu pai e a tua mãe, que é o primeiro mandamento com promessa. (Efésios 6:2)",
  "Tenho por certo que aquele que começou uma boa obra em vós a aperfeiçoará até ao dia de Jesus Cristo. (Filipenses 1:6)",
  "Para mim o viver é Cristo, e o morrer é ganho. (Filipenses 1:21)",
  "Nada façais por contenda ou por vanglória, mas por humildade; cada um considere os outros superiores a si mesmo. (Filipenses 2:3)",
  "Nada façam por ambição egoísta ou por vaidade, mas humildemente considerem os outros superiores a si mesmos. (Filipenses 2:3)",
  "Tende em vós aquele sentimento que houve também em Cristo Jesus. (Filipenses 2:5)",
  "Fazei todas as coisas sem murmurações nem contendas. (Filipenses 2:14)",
  "Alegrai-vos sempre no Senhor; outra vez digo, alegrai-vos. (Filipenses 4:4)",
  "Seja a vossa equidade notória a todos os homens. Perto está o Senhor. (Filipenses 4:5)",
  "Não estejais inquietos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração. (Filipenses 4:6)",
  "E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus. (Filipenses 4:7)",
  "Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro... nisso pensai. (Filipenses 4:8)",
  "Posso todas coisas naquele que me fortalece. (Filipenses 4:13)",
  "O meu Deus, segundo as suas riquezas, suprirá todas as vossas necessidades em glória, por Cristo Jesus. (Filipenses 4:19)",
  "Ele nos tirou do poder das trevas, e nos transportou para o reino do Filho do seu amor. (Colossenses 1:13)",
  "Portanto, se já ressuscitastes com Cristo, buscai as coisas que são de cima, onde Cristo está assentado à destra de Deus. (Colossenses 3:1)",
  "Pensai nas coisas que são de cima, e não nas que são de terra. (Colossenses 3:2)",
  "Revesti-vos, pois, como eleitos de Deus, santos e amados, de entranhas de misericórdia, de benignidade, humildade. (Colossenses 3:12)",
  "Suportando-vos uns aos outros, e perdoando-vos uns aos outros, se alguém tiver queixa contra outro. (Colossenses 3:13)",
  "Mas, sobretudo, revesti-vos do amor, que é o vínculo da perfeição. (Colossenses 3:14)",
  "E a paz de Deus, para a qual também fostes chamados em um corpo, domine em vossos corações; e sede agradecidos. (Colossenses 3:15)",
  "A palavra de Cristo habite em vós abundantemente, em toda a sabedoria. (Colossenses 3:16)",
  "E, tudo quanto fizerdes por palavras ou por obras, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai. (Colossenses 3:17)",
  "E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor, e não aos homens. (Colossenses 3:23)",
  "Sabendo que recebereis do Senhor o galardão da herança, porque a Cristo, o Senhor, servis. (Colossenses 3:24)",
  "Perseverai em oração, velando nela com ação de graças. (Colossenses 4:2)",
  "A vossa palavra seja sempre agradável, temperada com sal, para que saibais como vos convém responder a cada um. (Colossenses 4:6)",
  "Lembrando-nos sem cessar da obra da vossa fé, do trabalho do vosso amor, e da paciência da vossa esperança. (1 Tessalonicenses 1:3)",
  "Porque o Senhor mesmo descerá do céu com alarido, e com voz de arcanjo, e com a trombeta de Deus. (1 Tessalonicenses 4:16)",
  "Consolai-vos, pois, uns aos outros com estas palavras. (1 Tessalonicenses 4:18)",
  "Regozijai-vos sempre. (1 Tessalonicenses 5:16)",
  "Orai sem cessar. (1 Tessalonicenses 5:17)",
  "Em tudo dai graças, porque esta é a vontade de Deus em Cristo Jesus para convosco. (1 Tessalonicenses 5:18)",
  "Não extingais o Espírito. (1 Tessalonicenses 5:19)",
  "Não desprezeis as profecias. (1 Tessalonicenses 5:20)",
  "Examinai tudo. Retende o que é bom. (1 Tessalonicenses 5:21)",
  "Abstende-vos de toda a aparência do mal. (1 Tessalonicenses 5:22)",
  "E o mesmo Deus de paz vos santifique em tudo; e todo o vosso espírito, e alma, e corpo, sejam conservados íntegros. (1 Tessalonicenses 5:23)",
  "Fiel é o que vos chama, o qual também o fará. (1 Tessalonicenses 5:24)",
  "Mas o Senhor é fiel; ele os fortalecerá e os guardará do Maligno. (2 Tessalonicenses 3:3)",
  "E o Senhor dirija os vossos corações no amor de Deus, e na paciência de Cristo. (2 Tessalonicenses 3:5)",
  "E vós, irmãos, não vos canseis de fazer o bem. (2 Tessalonicenses 3:13)",
  "Ora, o mesmo Senhor da paz vos dê sempre paz de toda a maneira. O Senhor seja com todos vós. (2 Tessalonicenses 3:16)",
  "Ora, o fim do mandamento é o amor de um coração puro, e de uma boa consciência, e de uma fé não fingida. (1 Timóteo 1:5)",
  "Porque há um só Deus, e um só Mediador entre Deus e os homens, Jesus Cristo homem. (1 Timóteo 2:5)",
  "Ninguém despreze a tua mocidade; mas sê o exemplo dos fiéis, na palavra, no trato, no amor, no espírito, na fé, na pureza. (1 Timóteo 4:12)",
  "Persiste em ler, exortar e ensinar, até que eu vá. (1 Timóteo 4:13)",
  "Não desprezes o dom que há em ti. (1 Timóteo 4:14)",
  "Mas é grande ganho a piedade com contentamento. (1 Timóteo 6:6)",
  "Porque nada trouxemos para este mundo, e manifesto é que nada podemos levar dele. (1 Timóteo 6:7)",
  "Porque o amor ao dinheiro é a raiz de toda a espécie de males. (1 Timóteo 6:10)",
  "Combate o bom combate da fé, toma posse da vida eterna, para a qual também foste chamado. (1 Timóteo 6:12)",
  "Manda aos ricos deste mundo que não sejam altivos, nem ponham a esperança na incerteza das riquezas, mas em Deus. (1 Timóteo 6:17)",
  "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação. (2 Timóteo 1:7)",
  "Não te envergonhes, pois, do testemunho de nosso Senhor. (2 Timóteo 1:8)",
  "Porque eu sei em quem tenho crido, e estou certo de que é poderoso para guardar o meu depósito até àquele dia. (2 Timóteo 1:12)",
  "Tu, pois, meu filho, fortifica-te na graça que há em Cristo Jesus. (2 Timóteo 2:1)",
  "Sofre, pois, comigo, as aflições, como bom soldado de Jesus Cristo. (2 Timóteo 2:3)",
  "Considera o que digo, e o Senhor te dê entendimento em tudo. (2 Timóteo 2:7)",
  "Palavra fiel é esta: que, se morrermos com ele, também com ele viveremos. (2 Timóteo 2:11)",
  "Se sofrermos, também com ele reinaremos; se o negarmos, também ele nos negará. (2 Timóteo 2:12)",
  "Se formos infiéis, ele permanece fiel; não pode negar-se a si mesmo. (2 Timóteo 2:13)",
  "Procura apresentar-te a Deus aprovado, como obreiro que não tem de que se envergonhar, que maneja bem a palavra da verdade. (2 Timóteo 2:15)",
  "Fugia também das paixões da mocidade; e segue a justiça, a fé, o amor, e a paz com os que... invocam o Senhor. (2 Timóteo 2:22)",
  "E ao servo do Senhor não convém contender, mas sim, ser manso para com todos, apto para ensinar, sofredor. (2 Timóteo 2:24)",
  "Toda a Escritura é divinamente inspirada, e proveitosa para ensinar, para redarguir, para corrigir, para instruir. (2 Timóteo 3:16)",
  "Que o homem de Deus seja perfeito, e perfeitamente instruído para toda a boa obra. (2 Timóteo 3:17)",
  "Conjuro-te, pois, diante de Deus... que pregues a palavra, instes a tempo e fora de tempo. (2 Timóteo 4:1-2)",
  "Mas tu, sê sóbrio em tudo, sofre as aflições, faze a obra de um evangelista, cumpre o teu ministério. (2 Timóteo 4:5)",
  "Combati o bom combate, acabei a carreira, guardei a fé. (2 Timóteo 4:7)",
  "Desde agora, a coroa da justiça me está guardada, a qual o Senhor, justo juiz, me dará naquele dia. (2 Timóteo 4:8)",
  "O Senhor me livrará de toda a má obra, e guardar-me-á para o seu reino celestial; a quem seja glória para todo o sempre. (2 Timóteo 4:18)",
  "A graça seja com todos vós. Amém. (Tito 3:15)",
  "A graça de nosso Senhor Jesus Cristo seja com o vosso espírito. Amém. (Filemom 1:25)",
  "Havendo Deus antigamente falado muitas vezes, e de muitas maneiras, aos pais, pelos profetas, a nós falou-nos nestes últimos dias pelo Filho. (Hebreus 1:1)",
  "Porque a palavra de Deus é viva e eficaz, e mais penetrante do que espada alguma de dois gumes. (Hebreus 4:12)",
  "Cheguemos, pois, com confiança ao trono da graça, para que possamos alcançar misericórdia e achar graça. (Hebreus 4:16)",
  "Ainda que era Filho, aprendeu a obediência, por aquilo que sofreu. (Hebreus 5:8)",
  "Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que se não veem. (Hebreus 11:1)",
  "Pela fé entendemos que os mundos pela palavra de Deus foram criados. (Hebreus 11:3)",
  "Sem fé é impossível agradar-lhe; porque é necessário que aquele que se aproxima de Deus creia que ele existe. (Hebreus 11:6)",
  "Portanto nós também, pois que estamos rodeados de uma tão grande nuvem de testemunhas, deixemos todo o embaraço. (Hebreus 12:1)",
  "Corramos com paciência a carreira que nos está proposta, olhando para Jesus, autor e consumador da fé. (Hebreus 12:1-2)",
  "Segui a paz com todos, e a santificação, sem a qual ninguém verá o Senhor. (Hebreus 12:14)",
  "Permaneça o amor fraternal. (Hebreus 13:1)",
  "Não vos esqueçais da hospitalidade, porque por ela alguns, não o sabendo, hospedaram anjos. (Hebreus 13:2)",
  "Seja a vossa vida isenta de avareza, contentando-vos com o que tendes. (Hebreus 13:5)",
  "O Senhor é o meu ajudador, e não temerei o que me possa fazer o homem. (Hebreus 13:6)",
  "Jesus Cristo é o mesmo, ontem, e hoje, e eternamente. (Hebreus 13:8)",
  "Não vos deixeis levar por doutrinas várias e estranhas, porque bom é que o coração se fortifique com graça. (Hebreus 13:9)",
  "E não vos esqueçais da beneficência e partilha, porque com tais sacrifícios Deus se agrada. (Hebreus 13:16)",
  "Obedecei a vossos pastores, e sujeitai-vos a eles; porque velam por vossas almas. (Hebreus 13:17)",
  "O Deus de paz... vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade. (Hebreus 13:20-21)",
  "Meus irmãos, tende grande gozo quando cairdes em várias tentações; sabendo que a prova da vossa fé produz a paciência. (Tiago 1:2-3)",
  "Tenha, porém, a paciência a sua obra perfeita, para que sejais perfeitos e completos, sem faltar em coisa alguma. (Tiago 1:4)",
  "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente, e não o lança em rosto. (Tiago 1:5)",
  "Peça-a, porém, com fé, em nada duvidando; porque o que duvida é semelhante à onda do mar, que é levada pelo vento. (Tiago 1:6)",
  "Bem-aventurado o homem que suporta a tentação; porque, quando for provado, receberá a coroa da vida. (Tiago 1:12)",
  "Toda a boa dádiva e todo o dom perfeito vem do alto, descendo do Pai das luzes, em quem não há mudança. (Tiago 1:17)",
  "Portanto, meus amados irmãos, todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar. (Tiago 1:19)",
  "Porque a ira do homem não opera a justiça de Deus. (Tiago 1:20)",
  "E sede cumpridores da palavra, e não somente ouvintes, enganando-vos a vós mesmos. (Tiago 1:22)",
  "A religião pura e imaculada para com Deus, o Pai, é esta: Visitar os órfãos e as viúvas nas suas tribulações. (Tiago 1:27)",
  "Porque, assim como o corpo sem o espírito está morto, assim também a fé sem obras está morta. (Tiago 2:26)",
  "Mas a sabedoria que do alto vem é, primeiramente pura, depois pacífica, moderada, tratável, cheia de misericórdia. (Tiago 3:17)",
  "Ora, o fruto da justiça semeia-se na paz, para aqueles que exercitam a paz. (Tiago 3:18)",
  "Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós. (Tiago 4:7)",
  "Chegai-vos a Deus, e ele se chegará a vós. (Tiago 4:8)",
  "Humilhai-vos perante o Senhor, e ele vos exaltará. (Tiago 4:10)",
  "Aquele, pois, que sabe fazer o bem e não o faz, comete pecado. (Tiago 4:17)",
  "Está alguém entre vós aflito? Ore. Está alguém contente? Cante louvores. (Tiago 5:13)",
  "A oração feita por um justo pode muito em seus efeitos. (Tiago 5:16)",
  "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo que, segundo a sua grande misericórdia, nos gerou de novo. (1 Pedro 1:3)",
  "Para uma herança incorruptível, incontaminável, e que se não pode murchar, guardada nos céus para vós. (1 Pedro 1:4)",
  "Como filhos obedientes, não vos conformando com as concupiscências que antes havia na vossa ignorância. (1 Pedro 1:14)",
  "Mas, como é santo aquele que vos chamou, sede vós também santos em toda a vossa maneira de viver. (1 Pedro 1:15)",
  "Porque toda a carne é como a erva, e toda a glória do homem como a flor da erva. Secou-se a erva, e caiu a sua flor. (1 Pedro 1:24)",
  "Mas a palavra do Senhor permanece para sempre. E esta é a palavra que vos foi evangelizada. (1 Pedro 1:25)",
  "Desejai afetuosamente, como meninos novamente nascidos, o leite espiritual, não falsificado, para que por ele cresçais. (1 Pedro 2:2)",
  "Mas vós sois a geração eleita, o sacerdócio real, a nação santa, o povo adquirido, para que anuncieis as virtudes. (1 Pedro 2:9)",
  "Honrai a todos. Amai a fraternidade. Temei a Deus. Honrai o rei. (1 Pedro 2:17)",
  "Porque para isto fostes chamados; pois também Cristo padeceu por nós, deixando-nos o exemplo, para que sigais as suas pisadas. (1 Pedro 2:21)",
  "O qual não cometeu pecado, nem na sua boca se achou engano. (1 Pedro 2:22)",
  "Levando ele mesmo em seu corpo os nossos pecados sobre o madeiro, para que, mortos para os pecados, vivamos para a justiça. (1 Pedro 2:24)",
  "E, finalmente, sede todos de um mesmo sentimento, compassivos, amando os irmãos, entranháveis, misericordiosos, afáveis. (1 Pedro 3:8)",
  "Não retribuindo mal por mal, ou injúria por injúria; antes, pelo contrário, bendizendo. (1 Pedro 3:9)",
  "Porque os olhos do Senhor estão sobre os justos, e os seus ouvidos atentos às suas orações. (1 Pedro 3:12)",
  "Antes, santificai a Cristo, como Senhor, em vossos corações; e estai sempre preparados para responder com mansidão. (1 Pedro 3:15)",
  "Mas, sobretudo, tende ardente amor uns para com os outros; porque o amor cobrirá uma multidão de pecados. (1 Pedro 4:8)",
  "Sendo hospitaleiros uns para com os outros, sem murmurações. (1 Pedro 4:9)",
  "Cada um administre aos outros o dom como o recebeu, como bons despenseiros da multiforme graça de Deus. (1 Pedro 4:10)",
  "Humilhai-vos, pois, debaixo da potente mão de Deus, para que a seu tempo vos exalte. (1 Pedro 5:6)",
  "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós. (1 Pedro 5:7)",
  "Sede sóbrios; vigiai; porque o diabo, vosso adversário, anda em derredor, bramando como leão, buscando a quem possa devorar. (1 Pedro 5:8)",
  "E o Deus de toda a graça... depois de haverdes padecido um pouco, ele mesmo vos aperfeiçoará, confirmará, fortificará. (1 Pedro 5:10)",
  "Paz seja com todos vós que estais em Cristo Jesus. Amém. (1 Pedro 5:14)",
  "Graça e paz vos sejam multiplicadas pelo conhecimento de Deus, e de Jesus nosso Senhor. (2 Pedro 1:2)",
  "Visto como o seu divino poder nos deu tudo o que diz respeito à vida e piedade, pelo conhecimento daquele que nos chamou. (2 Pedro 1:3)",
  "Pelas quais ele nos tem dado grandíssimas e preciosas promessas, para que por elas fiqueis participantes da natureza divina. (2 Pedro 1:4)",
  "E vós também, pondo nisto mesmo toda a diligência, acrescentai à vossa fé a virtude, e à virtude a ciência. (2 Pedro 1:5)",
  "E à ciência o temperamento, e ao temperamento a paciência, e à paciência a piedade. (2 Pedro 1:6)",
  "E à piedade o amor fraternal, e ao amor fraternal a caridade. (2 Pedro 1:7)",
  "Antes crescei na graça e conhecimento de nosso Senhor e Salvador, Jesus Cristo. A ele seja dada a glória. (2 Pedro 3:18)",
  "E a vida foi manifestada, e nós a vimos, e testificamos dela, e vos anunciamos a vida eterna, que estava com o Pai. (1 João 1:2)",
  "E a nossa comunhão é com o Pai, e com seu Filho Jesus Cristo. (1 João 1:3)",
  "E estas coisas vos escrevemos, para que o vosso gozo se cumpra. (1 João 1:4)",
  "E esta é a mensagem que dele ouvimos, e vos anunciamos: que Deus é luz, e não há nele trevas nenhumas. (1 João 1:5)",
  "Se dissermos que temos comunhão com ele, e andarmos em trevas, mentimos, e não praticamos a verdade. (1 João 1:6)",
  "Mas, se andarmos na luz, como ele na luz está, temos comunhão uns com os outros, e o sangue de Jesus Cristo nos purifica. (1 João 1:7)",
  "Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda a injustiça. (1 João 1:9)",
  "Meus filhinhos, estas coisas vos escrevo, para que não pequeis; e, se alguém pecar, temos um Advogado para com o Pai, Jesus Cristo. (1 João 2:1)",
  "Qualquer que nega o Filho, também não tem o Pai; aquele que confessa o Filho, tem também o Pai. (1 João 2:23)",
  "Vejam como é grande o amor que o Pai nos concedeu: que fôssemos chamados filhos de Deus, o que de fato somos! (1 João 3:1)",
  "Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade. (1 João 3:18)",
  "E este é o seu mandamento: que creiamos no nome de seu Filho Jesus Cristo, e nos amemos uns aos outros, segundo o mandamento. (1 João 3:23)",
  "Amados, amemo-nos uns aos outros; porque o amor é de Deus; e qualquer que ama é nascido de Deus e conhece a Deus. (1 João 4:7)",
  "Aquele que não ama não conhece a Deus; porque Deus é amor. (1 João 4:8)",
  "Nisto se manifestou o amor de Deus para conosco: que Deus enviou seu Filho unigênito ao mundo, para que por ele vivamos. (1 João 4:9)",
  "Nisto está o amor, não em que nós tenhamos amado a Deus, mas em que ele nos amou a nós, e enviou seu Filho para propiciação. (1 João 4:10)",
  "Amados, se Deus assim nos amou, também nós devemos amar uns aos outros. (1 João 4:11)",
  "Ninguém jamais viu a Deus; se nos amamos uns aos outros, Deus está em nós, e em nós é perfeito o seu amor. (1 João 4:12)",
  "Nós amamos porque ele nos amou primeiro. (1 João 4:19)",
  "Se alguém diz: Eu amo a Deus, e odeia a seu irmão, é mentiroso. Pois quem não ama a seu irmão, ao qual viu, como pode amar a Deus? (1 João 4:20)",
  "E dele temos este mandamento: que quem ama a Deus, ame também a seu irmão. (1 João 4:21)",
  "Porque este é o amor de Deus: que guardemos os seus mandamentos; e os seus mandamentos não são pesados. (1 João 5:3)",
  "Porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo, a nossa fé. (1 João 5:4)",
  "E o testemunho é este: que Deus nos deu a vida eterna; e esta vida está em seu Filho. (1 João 5:11)",
  "Quem tem o Filho tem a vida; quem não tem o Filho de Deus não tem a vida. (1 João 5:12)",
  "Estas coisas vos escrevi a vós, os que credes no nome do Filho de Deus, para que saibais que tendes a vida eterna. (1 João 5:13)",
  "E esta é a confiança que temos nele, que, se pedirmos alguma coisa, segundo a sua vontade, ele nos ouve. (1 João 5:14)",
  "E, se sabemos que nos ouve em tudo o que pedimos, sabemos que alcançamos as petições que lhe limitamos. (1 João 5:15)",
  "Nós sabemos que somos de Deus, e que todo o mundo está no maligno. (1 João 5:19)",
  "E sabemos que já o Filho de Deus é vindo, e nos deu entendimento para conhecermos o que é verdadeiro. (1 João 5:20)",
  "E o amor é este: que andemos segundo os seus mandamentos. Este é o mandamento, como ouviste desde o princípio. (2 João 1:6)",
  "Amado, desejo que te vá bem em todas as coisas, e que tenhas saúde, assim como bem vai a tua alma. (3 João 1:2)",
  "Não tenho maior gozo do que este, o de ouvir que os meus filhos andam na verdade. (3 João 1:4)",
  "Amado, segues o que é bom. Quem faz o bem é de Deus; mas quem faz o mal não tem visto a Deus. (3 João 1:11)",
  "Àquele que é poderoso para vos guardar de tropeçar, e apresentar-vos irrepreensíveis, com alegria, perante a sua glória. (Judas 1:24)",
  "Ao único Deus sábio, Salvador nosso, seja glória e majestade, domínio e poder, agora, e para todo o sempre. Amém. (Judas 1:25)",
  "Revelação de Jesus Cristo, a qual Deus lhe deu, para mostrar aos seus servos as coisas que brevemente devem acontecer. (Apocalipse 1:1)",
  "Bem-aventurado aquele que lê, e os que ouvem as palavras desta profecia, e guardam as coisas que nela estão escritas. (Apocalipse 1:3)",
  "Graça e paz vos sejam dadas da parte daquele que é, e que era, e que há de vir. (Apocalipse 1:4)",
  "Eu sou o Alfa e o Ômega, o princípio e o fim, diz o Senhor, que é, e que era, e que há de vir, o Todo-Poderoso. (Apocalipse 1:8)",
  "Não temas; eu sou o Primeiro e o Último; e o que vive; fui morto, mas eis aqui estou vivo para todo o sempre. Amém. (Apocalipse 1:17-18)",
  "Sê fiel até à morte, e dar-te-ei a coroa da vida. (Apocalipse 2:10)",
  "Eis que estou à porta, e bato; se alguém ouvir a minha voz, e abrir a porta, entrarei em sua casa, e com ele cearei. (Apocalipse 3:20)",
  "Digno és, Senhor, de receber glória, e honra, e poder; porque tu criaste todas as coisas. (Apocalipse 4:11)",
  "E Deus limpará de seus olhos toda a lágrima; e não haverá mais morte, nem clamor, nem dor. (Apocalipse 21:4)",
  "Eu sou o Alfa e o Ômega, o princípio e o fim. A quem quer que tiver sede, de graça lhe darei da fonte da água da vida. (Apocalipse 21:6)",
  "E mostrou-me o rio puro da água da vida, claro como cristal, que procedia do trono de Deus e do Cordeiro. (Apocalipse 22:1)",
  "Eu sou a Raiz e a Geração de Davi, a brilhante Estrela da manhã. (Apocalipse 22:16)",
  "E o Espírito e a esposa dizem: Vem. E quem ouve, diga: Vem. E quem tem sede, venha; e quem quiser, tome de graça da água da vida. (Apocalipse 22:17)",
  "Aquele que testifica estas coisas diz: Certamente cedo venho. Amém. Ora vem, Senhor Jesus. (Apocalipse 22:20)",
  "A graça de nosso Senhor Jesus Cristo seja com todos vós. Amém. (Apocalipse 22:21)",
  "No princípio, criou Deus os céus e a terra. (Gênesis 1:1)",
  "E disse Deus: Haja luz; e houve luz. (Gênesis 1:3)",
  "E viu Deus tudo quanto tinha feito, e eis que era muito bom. (Gênesis 1:31)",
  "Ora, o Senhor disse a Abrão: Sai-te da tua terra... e vai para a terra que eu te mostrarei. (Gênesis 12:1)",
  "E far-te-ei uma grande nação, e abençoar-te-ei e engrandecerei o teu nome; e tu serás uma bênção. (Gênesis 12:2)",
  "Eu sou o Deus Todo-Poderoso; anda em minha presença e sê perfeito. (Gênesis 17:1)",
  "Haveria coisa alguma difícil ao Senhor? (Gênesis 18:14)",
  "O Senhor é a minha força, e o meu cântico; ele se tem tornado a minha salvação. (Êxodo 15:2)",
  "Se ouvires atento a voz do Senhor teu Deus... nenhuma das enfermidades porei sobre ti... porque eu sou o Senhor que te sara. (Êxodo 15:26)",
  "O Senhor pelejará por vós, e vós vos calareis. (Êxodo 14:14)",
  "A minha presença irá contigo, e eu te darei descanso. (Êxodo 34:14)",
  "O Senhor, o Senhor Deus, misericordioso e piedoso, tardio em irar-se e grande em beneficência e verdade. (Êxodo 34:6)",
  "Santos sereis, porque eu, o Senhor vosso Deus, sou santo. (Levítico 19:2)",
  "O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti, e tenha misericórdia de ti. (Números 6:24-25)",
  "O Senhor sobre ti levante o seu rosto e te dê a paz. (Números 6:26)",
  "Deus não é homem, para que minta; nem filho do homem, para que se arrependa; porventura diria ele, e não o faria? (Números 23:19)",
  "Amarás, pois, o Senhor teu Deus de todo o teu coração, e de toda a tua alma, e de todas as tuas forças. (Deuteronômio 6:5)",
  "E estas palavras, que hoje te ordeno, estarão no teu coração. (Deuteronômio 6:6)",
  "Nem só de pão viverá o homem, mas de tudo o que sai da boca do Senhor viverá o homem. (Deuteronômio 8:3)",
  "O Senhor teu Deus é o Deus de deuses, e o Senhor de senhores, o Deus grande, poderoso e terrível. (Deuteronômio 10:17)",
  "Porque o Senhor teu Deus é um Deus misericordioso; não te desamparará, nem te destruirá. (Deuteronômio 4:31)",
  "Guarda-te, que não te esqueças do Senhor teu Deus. (Deuteronômio 8:11)",
  "Eu te ordenei: Sê forte e corajoso; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andes. (Josué 1:9)",
  "Não se aparte da tua boca o livro desta lei; antes medita nele dia e noite, para que tenhas cuidado de fazer conforme tudo. (Josué 1:8)",
  "Eu e a minha casa serviremos ao Senhor. (Josué 24:15)",
  "Assim pereçam todos os teus inimigos, ó Senhor! Mas os que o amam sejam como o sol quando sai na sua força. (Juízes 5:31)",
  "Não me instes para que te deixe... porque aonde quer que fores irei eu, e onde quer que pousares, pousarei eu; o teu povo é o meu. (Rute 1:16)",
  "Não há santo como é o Senhor; porque não há outro fora de ti; e rocha nenhuma há como o nosso Deus. (1 Samuel 2:2)",
  "Porque o Senhor não vê como vê o homem, pois o homem vê o que está diante dos olhos, porém o Senhor olha para o coração. (1 Samuel 16:7)",
  "Até aqui nos ajudou o Senhor. (1 Samuel 7:12)",
  "Tão-somente temei ao Senhor, e servi-o fielmente de todo o vosso coração; pois vede quão grandiosas coisas vos fez. (1 Samuel 12:24)",
  "O Senhor vive; e bendito seja o meu rochedo, e exaltado seja Deus, a rocha da minha salvação! (2 Samuel 22:47)",
  "Dá, pois, ao teu servo um coração entendido para julgar o teu povo, para que prudentemente discirna entre o bem e o mal. (1 Reis 3:9)",
  "E disse: Ó Senhor Deus de Israel, não há Deus como tu, em cima nos céus nem embaixo na terra. (1 Reis 8:23)",
  "Buscai ao Senhor e a sua força; buscai a sua face continuamente. (1 Crônicas 16:11)",
  "Dai graças ao Senhor, porque ele é bom; porque a sua benignidade dura para sempre. (1 Crônicas 16:34)",
  "Tua é, Senhor, a magnificência, e o poder, e a honra, e a vitória, e a majestade; porque teu é tudo quanto há nos céus. (1 Crônicas 29:11)",
  "O Senhor, nosso Deus, é misericordioso e compassivo, e não desviará de nós o seu rosto, se voltarmos para ele. (2 Crônicas 30:9)",
  "A alegria do Senhor é a vossa força. (Neemias 8:10)",
  "O Senhor deu, e o Senhor tirou; bendito seja o nome do Senhor. (Jó 1:21)",
  "Porque eu sei que o meu Redentor vive, e que por fim se levantará sobre a terra. (Jó 19:25)",
  "Ele conhece o meu caminho; provando-me ele, sairei como o ouro. (Jó 23:10)",
  "O espírito de Deus me fez; e a inspiração do Todo-Poderoso me deu vida. (Jó 33:4)"
];

export function getVerseForDay(dayOfYear: number, month?: number): string {
    try {
        if (typeof window !== 'undefined') {
            const custom = window.localStorage.getItem('agendamaster_custom_verses');
            if (custom) {
                const parsed = JSON.parse(custom);
                if (Array.isArray(parsed) && parsed.length > 0) {
                    if (month !== undefined && month >= 0 && month < 12) {
                        return parsed[month % parsed.length];
                    }
                    return parsed[dayOfYear % parsed.length];
                }
            }
        }
    } catch (e) {
        console.error('Error loading custom verses', e);
    }
    if (month !== undefined && month >= 0 && month < 12 && BIBLE_VERSES.length > 0) {
        return BIBLE_VERSES[month % BIBLE_VERSES.length];
    }
    return BIBLE_VERSES[dayOfYear % BIBLE_VERSES.length];
}
